site_name: Руководство по FastStream для новичков
site_description: Руководство по FastStream для новичков
site_author: Sergey Yavorsky
site_url: https://maclovi.github.io/faststream-tutorial/

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand

repo_url: https://github.com/Maclovi/faststream-tutorial
repo_name: Maclovi/faststream-tutorial

nav:
  - Главная: index.md
  - Что такое брокеры сообщений?: introduction.md
  - Установка и настройка: setup.md
  - Первое приложение: first_app.md
  - Pydantic: pydantic.md
  - Тестирование: testing.md
  - Документация: documentation.md
  - Что дальше?: next_steps.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            heading_level: 3
            show_root_heading: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - attr_list
  - def_list
  - smarty
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
