name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install Dependencies and library
        run: uv pip install --system "."

      # - name: Lint Markdown
      #   run: |
      #     npm install -g markdownlint-cli
      #     markdownlint docs/**/*.md

      - name: Build MkDocs
        run: mkdocs build -f docs/mkdocs.yml

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: docs/site
